### ISSUE TITLE
[Feature Request] add Role|Binding and ServiceAccount Types

### ISSUE THREAD

**Issue by adrpp** [jenkinsci/kubernetes-cd-plugin#110]
Hello,

are some further types going to be supported, like Role, RoleBinding and ServiceAccounts ?
Using 2.1.2 plugin version, mentioned types are not supported resulting in:

Skipped unsupported resource: class V1Role {
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
...
...
}

[Here](https://github.com/jenkinsci/kubernetes-cd-plugin/blob/dev/src/main/java/io/kubesphere/jenkins/kubernetes/generated/KubernetesModelClasses.java#L328) are mentioned objects listed, however your [list of supported types](https://github.com/jenkinsci/kubernetes-cd-plugin#resource-types) does not list those (which is correct).

Thanks,
Adrian

**Comment by runzexia** [comment]
https://github.com/jenkinsci/kubernetes-cd-plugin/pull/117
