### ISSUE TITLE
Class not found: io.kubernetes.client.openapi.models.V1Service

### ISSUE THREAD

**Issue by ldvy** [jenkinsci/kubernetes-cd-plugin#135]
Hello guys, I get the following error when trying to use the YAML file from my GitRepo to deploy to kube cluster.
![image](https://user-images.githubusercontent.com/54864885/86305216-cc89ab00-bc19-11ea-8bf0-c62c5206c030.png)

Here is the content of my .yaml file:
![image](https://user-images.githubusercontent.com/54864885/86305500-7cf7af00-bc1a-11ea-8aee-cca6407fa2f2.png)

I've already tried changing the ports, the API version to `apps/v1`, etc.
What seems weird to me is that no matter which line goes foirst in the file, it always shows me the same issue.
What can be causing this?

**Comment by kellycampbell** [comment]
Similar problem in #134 

What version of Kubernetes are you using?

**Comment by renedare** [comment]
I have the same problem running Kubernetes v1.18.3. I'm running Jenkins v2.235.1 and all my plugins are up to date.

The workaround I've found for now is to downgrade Jackson 2 API to v2.10.3 and to downgrade Snakeyaml API to v1.26.2. If those 2 plugins are updated to their respective latest versions, the error message comes back.

**Comment by ldvy** [comment]
I found the root cause of this behaviour. Jackson 2 API plugin version 2.11.1 is breaking kube deployments; you can find more info by the link below:
https://issues.jenkins-ci.org/browse/JENKINS-62995

Downgrading the following plugins worked for me: Jackson 2 API v2.10.0,
Kubernetes v1.21.3,
Kubernetes Client API v4.6.3-1,
Kubernetes Continuous Deploy v2.1.2,
Kubernetes Credentials v0.5.0

As those plugins are default, you would need to find the relevant version source files in https://plugins.jenkins.io/, and upload them to your Jenkins server by going
Manage Jenkins --> Manage Plugins --> Advanced --> Upload Plugin section
