### ISSUE TITLE
Remove previous secrets and ReplicaSets after each CD

### ISSUE THREAD

**Issue by Novitoll** [jenkinsci/kubernetes-cd-plugin#14]
Currently, after each CD, there are useless `$KUBERNETES_SECRET_NAME` secrets and RSs. Some retention policy of these k8s objects will be beneficial.

**Comment by ArieShout** [comment]
The secret is created in Kubernetes and may be referenced by other resources, which is outside of the scope of the Jenkins plugin. It may be difficult to manage the life cycle of the secrets.

If those secrets with randomly generated names are causing trouble, you can set the `secretName` (Secret Name) in the configuration / Pipeline, and the plugin will create or update the secret with that name. Just keep in mind that if there's some update to the secret, the resources that relies on the original secret may be affected in this case.

**Comment by Novitoll** [comment]
I do use secretName in my pipeline and I know  that it's used also in Replica Set, but need to add those resources retaining policy

BTW, what about rollback? (another issue) can not see in docs

**Comment by ArieShout** [comment]
The resource life cycle varies for different user, and it's not practical to make assumptions in the plugin.

The rollback for Kubernetes can be implemented by applying the previous resource configuration, which you can do it in a separate Jenkins job, or manually from command line.
