### ISSUE TITLE
Messages class not found

### ISSUE THREAD

**Issue by edana-dev** [jenkinsci/kubernetes-cd-plugin#15]
Hi, I cloned this project and wanna build on my machine, but got an error like "Cannot resolve symbol 'Message'"(com.microsoft.jenkins.kubernetes.Messages). Could you help me to fix it, tks!

**Comment by ArieShout** [comment]
The `Messages` class is generated from `Messages.properties`. You can run `mvn generate-sources` to generate the class.

Note the `generate-sources` will be invoked automatically in goals like `compile`, `package`, etc.

**Comment by edana-dev** [comment]
@ArieShout thanks for your kind reply! I got it.
