### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ChristofferNicklassonLenswayGroup** [jenkinsci/kubernetes-cd-plugin#16]
Hi,

Could you please provide some examples on how to then use it in a pipeline.
Lets say i want to update image for deployment FISH in namespace ocean

**Comment by ArieShout** [comment]
1. Prepare your Kubernetes resource configurations (YAML files) in your workspace. You need to specify the `namespace` in the configuration if it is not `default`.
1. Choose which authentication mechanism you want to use.
1. Use the `Pipeline Syntax` page to generate the pipeline configuration from Web UI.

![image](https://user-images.githubusercontent.com/423695/36954049-3b3c43a4-205a-11e8-9181-5300068bd65c.png)

**Comment by Novitoll** [comment]
```java
kubernetesDeploy(
                                    credentialsType: 'KubeConfig',
                                    kubeConfig: [path: "/path/to/config"],
                                    configs: 'deployment.yml',
                                    enableConfigSubstitution: true,
                                    secretNamespace: 'dev',
                                    secretName: "$BUILD_NUMBER".toString(),
                                    dockerCredentials: [
                                            [credentialsId: 'jenkins-key', server: "<registry>"]
                                    ]
                            )
```

**Comment by ArieShout** [comment]
close as no further response from the user.
