### ISSUE TITLE
Config Files Sample

### ISSUE THREAD

**Issue by eaydogan** [jenkinsci/kubernetes-cd-plugin#17]
5.Fill in the "Config Files" with the configuration file paths. Split multiple entries with comma (,). Ant glob syntax is supported for path patterns.

Which config files ? admin.conf ? And How we set it correctly. Please provide working example.

**Comment by ArieShout** [comment]
The "Config Files" refers to the Kubernetes resource configurations, such as configuration for deployments, pods, services, etc.

e.g.,

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

**Comment by ArieShout** [comment]
close as no further response from the user.
