### ISSUE TITLE
location of kube deployment file

### ISSUE THREAD

**Issue by gxbjtu** [jenkinsci/kubernetes-cd-plugin#18]
I tested the CD plugin and got an error: "ERROR: Config file /data/jenkins/kube_config was not found in workspace ...". It seems that deploy config files must be put in the workspace. But, in most cases, workspaces are different for different jobs and we need to manage the deployment files centrally. So, can the CD plugin support absolute path, or is there an alternative way?

**Comment by Novitoll** [comment]
Your kubeconfig is not available. Put your kubeconfig to Jenkins master and mount it to your Jenkins slave

**Comment by gxbjtu** [comment]
I don't think it is the matter of kube-config. All the Jenkins nodes use the same directory shared by nfs. As the error I mentioned, It runs correctly when I use relative directory in workspace. The tests I have done: 
1. When I set the workspace to "/data/jenkins/test/" and set file path to "/data/jenkins/kube_config/config", error of config file not found appears.
2. When I set the workspace to "/data/jenkins/kube_config" and set file path to "config", it runs ok.

**Comment by ArieShout** [comment]
The current implementation searches the kubeconfig in the workspace directory. It may be better to:
* look up in the workspace directory if the given path is relative
* look up in system directory if the given path is absolute

**Comment by gxbjtu** [comment]
The kubeconfig file can be found by relative path or absolute path. But the deployment file (e.g. test.yml) can only be found by relative path. Is it right?

**Comment by ArieShout** [comment]
yes, generally that is project and environment specific and it's likely to be stored along with the source code.

**Comment by ArieShout** [comment]
In release 0.2.0, the kubeconfig can be setup in the Jenkins credentials store, and referenced by the job configuration. We won't experience such path issue now.

The original configuration approach that is bound to the job configuration is deprecated.

**Comment by timur206** [comment]
So which solution ? How to resolve that problem ???
