### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by Huanqiang** [jenkinsci/kubernetes-cd-plugin#24]
Hello，I meet a problem when i deploy in jenkins, can you help me ?
![1522151908359](https://user-images.githubusercontent.com/7790051/37966067-d7530fe2-31f9-11e8-8696-7d418d672233.jpg)

and, this is my setting:
![1522152239467](https://user-images.githubusercontent.com/7790051/37966115-087872b0-31fa-11e8-9eb2-d621b55d31c8.jpg)

**Comment by Huanqiang** [comment]
I successfully published yesterday，but, today, I meet this problem, I have not changed any settings.

**Comment by ArieShout** [comment]
It seems the plugin failed to load / read your K8s resource configuration (`saiku.yaml`).

You may check if the file in your Jenkins workspace (e.g. in Ubuntu official Jenkins install this would be `/var/lib/jenkins/workspace/<job>/`) to see if it is corrupted, or dump the file before the K8s deploy to ensure it is not changed by accident.

**Comment by Huanqiang** [comment]
thx, now, it working, but i don't change anything, it's so crazy....
