### ISSUE TITLE
Still check deprecated kubeconfig file path with version 0.2.0

### ISSUE THREAD

**Issue by jiang-wei** [jenkinsci/kubernetes-cd-plugin#28]
I have the kubeconfig stored in the credentials store.

But it still checks for the deprecated kubeconfig file path

![image](https://user-images.githubusercontent.com/6143296/38514398-15cf277e-3bff-11e8-89a2-20e5d6259048.png)

**Comment by ArieShout** [comment]
This should be a false alert. You can ignore that for now.
I will fix that in the next release.

Thanks,

**Comment by jiang-wei** [comment]
One more thing, if I click the "Deprecateed Kubeconfig Settings", there is no way to fold the settings :(

**Comment by ArieShout** [comment]
fixed in release 0.2.1
