### ISSUE TITLE
ConfigMap Support

### ISSUE THREAD

**Issue by jiang-wei** [jenkinsci/kubernetes-cd-plugin#30]
I see it supports secrets, but why not support ConfigMap?

**Comment by ArieShout** [comment]
fixed in release 0.2.1

**Comment by Evanthx** [comment]
May I request a note in the Readme about how to use the configmap? I have been trying to use it and can't seem to make it work - the configmap doesn't get created in Kubernetes. I'm willing to bet I'm not configuring things right in the plugin, but I have no idea what to configure, and after reading some code still wasn't sure!

**Comment by Evanthx** [comment]
I should add I'm trying to do this in a Jenkinsfile in the pipeline!

**Comment by jslay88** [comment]
+1

I cannot seem to get this plugin to create ConfigMaps at all.
