### ISSUE TITLE
No "add build step" in job configuration.

### ISSUE THREAD

**Issue by Mosho1** [jenkinsci/kubernetes-cd-plugin#38]
I've installed the plugin, but there's no "add build step" that I can see. I also have the Build Pipeline plugin installed. I'm using a "GitHub organization" job. If this plugin doesn't work with that kind of job, the documentation should reflect it.

**Comment by ArieShout** [comment]
For Github organization jobs you need to write your pipeline which defines the build stages and push to your Github repo. You cannot configure the job steps from the GUI.

This is by design and not a problem with kubernetes-cd.
