### ISSUE TITLE
problem with docker registry credentials

### ISSUE THREAD

**Issue by slawekgh** [jenkinsci/kubernetes-cd-plugin#39]
my pipeline:
```
 kubernetesDeploy (
        configs: 'deployment.yaml',  
        kubeconfigId: 'kube1', 
        secretNamespace: 'default',
        secretName: 'registrycredentials',
        dockerCredentials: [
            [credentialsId: 'registry_creds', server: 'https://cent303:5000'],
        ],

    )
```
it creates secret "registrycredentials" in "default" kubernetes namespace:
```
kubectl get secret registrycredentials  --output="jsonpath={.data.\.dockercfg}" | base64 -d
{"https://index.docker.io/v1/":{"email":"admin","auth":"YWRtaW46YmFkbWlu"}}
```
BUT deployment CANNOT pull images from my private registry     

when I create this secret manually via:
```
kubectl create secret docker-registry registrycredentials --docker-server=cent303:5000 --docker-username=admin --docker-password=XXXXXX --docker-email=s@s.pl
```
this manually created secret seems a little bit different:
```
kubectl get secret registrycredentials  --output="jsonpath={.data.\.dockerconfigjson}" | base64 -d
{"auths":{"cent303:5000":{"username":"admin","password":"XXXXXX","email":"s@s.pl","auth":"YWRtaW46YmFkbWlu"}}}
```
and it works (deployment can pull images from my private registry)

of course my Jenkins "registry_creds" works fine with other pipeline parts (docker push, pull etc)

**Comment by slawekgh** [comment]
in official doc https://plugins.jenkins.io/kubernetes-cd there is "server" , 
but in other doc there is "url"
https://jenkins.io/doc/pipeline/steps/kubernetes-cd/#kubernetesdeploy-deploy-to-kubernetes

server doesnt work, url works 

seems there is a bug in doc

**Comment by ArieShout** [comment]
Hi @slawekgh , you're right the doc in the plugin home page is not consistent with the implementation. Thanks for pointing this out!

I have updated the documentation, however, it may take some time before it's synced to the home page.
