### ISSUE TITLE
Waiting for deployments

### ISSUE THREAD

**Issue by Mosho1** [jenkinsci/kubernetes-cd-plugin#44]
Is there a way I could wait for a deployment to finish (to run integration tests) in pipeline using this plugin?

**Comment by ArieShout** [comment]
The semantic of "finish" varies in different scenario:

* K8s accepted the deployment
* Replication Sets and pods are created for the deployment
* The startup of the applications in the pods finish
* The service endpoints detect that the pods are up and route traffic to the pods

The plugin currently returns once the first condition is met. You can setup some wait job (with timeout) before the tests.

**Comment by Mosho1** [comment]
Got it, thanks!
