### ISSUE TITLE
add 'delete' operations

### ISSUE THREAD

**Issue by dengqingpei1990** [jenkinsci/kubernetes-cd-plugin#45]
When using k8s canary deployment, we usually need to `delete` newer release and update the old one to the new version as the last step.  This plugin seems do not have some operations like `kubectl delete` which could do the delete operation in canary deployment.

So is there any way or new plans to config the plugin's operation not only include `kubectl create/apply` but also `kubectl delete`?  Thanks :)

**Comment by timwebster9** [comment]
I second this.  This plugin could also be used for CI, and we'd want to delete the resources after the testing completes.

**Comment by runzexia** [comment]
I want to support the deletion of resources. I would like to ask if you think that you should split a separate command for this operation, or is it acceptable to pass the parameter?
@gavinfish

**Comment by RhysMorgan1986** [comment]
This would be a great addition, saves the need for kubectl and additional mess in pipeline code.

**Comment by gavinfish** [comment]
Implemented in #98 .
