### ISSUE TITLE
apps/v1 for deployments not supported

### ISSUE THREAD

**Issue by rgreil** [jenkinsci/kubernetes-cd-plugin#50]
Looks like `extensions/v1beta1` is still expected for Deployments. When using `apps/v1`, the following error is shown for AKS deployments:

`o.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xxxx.hcp.eastus.azmk8s.io/apis/extensions/v1beta1/namespaces/default/deployments. Message: the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).`

Extract from deployment file:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:`

Deployment to this cluster with `apps/v1` kubectl works without issues.
Deployment to this cluster with `extensions/v1beta1` and kubernetes-cd-plugin+azure-acs-plugin works without issues.

**Comment by knan-nrk** [comment]
apps/v1 is The New Way since kubernetes v1.9. extensions/v1beta1 is deprecated. Can the plugin please be updated to tolerate this?

**Comment by tkuther** [comment]
Bumping the fabric8 kubernetes-client to v4.0.4 (https://github.com/jenkinsci/kubernetes-cd-plugin/blob/dev/pom.xml#L111) should solve this, see https://github.com/fabric8io/kubernetes-client/pull/1103

**Comment by dabeck** [comment]
@tkuther see my merge request.

**Comment by RichardKnowles** [comment]
+1. Shame this plugin seems to be dead, it ticked all of our boxes until we realised it's out of date.
