### ISSUE TITLE
Migrate Kubernetes Client

### ISSUE THREAD

**Issue by gavinfish** [jenkinsci/kubernetes-cd-plugin#67]
This plugin now uses [fabric8io kubernetes client](https://github.com/fabric8io/kubernetes-client) to access to kubernetes. But its legacy version seems not support modern API version which causes a lot issues here. It will be a good choice to replace this client with [Kubernetes Java Client](https://github.com/kubernetes-client/java) which is the official client library for kubernetes. This could help solve existing issues and enable new features of kubernetes.

**Comment by gavinfish** [comment]
hi @ArieShout , could you please help with merging the integration tests PR #6 before we start this.

**Comment by jiang-wei** [comment]
any update???

**Comment by gavinfish** [comment]
The Jenkins classloader prevents kubernetes-client to load its api models, details at kubernetes-client/java#474, any would be welcome to fix this issue.

**Comment by gavinfish** [comment]
Released as 2.0.0
