### ISSUE TITLE
Next step improve

### ISSUE THREAD

**Issue by runzexia** [jenkinsci/kubernetes-cd-plugin#79]
1. There are more and more projects using CRD in k8s, such as istios, knavie, etc.
I think we should get the api version and other information from the yaml file and create and update it.
We can implement a function similar to kubectl apply
2.  Switch client to kubernetes-client java
3. add a context to pipline run to see what resources are deployed
……

@gavinfish @MyronFanQiu 
I hope to get feedback from you on my thoughts. @soulseen and I can provide some help.

**Comment by gavinfish** [comment]
Hi @runzexia ,

1. For the fabric8io sdk, it will parse the yaml file into its definition classes with api version. I do not know much details about kubectl apply. It will be great if the plugin can deploy general CRD.

2. Indeed I created a PR #69 to switch the sdk, but the Jenkins classloader issue kubernetes-client/java#474 prevents it to load all the api models. Hope you can give some advice to fix this problem.

3. This feature makes sense to me.

Any contribution here is welcome!

**Comment by MyronFanQiu** [comment]
Hi @runzexia Thanks for opening this issue. It's great. From my side, I just think we should be careful about switching client to java kubernetes-client. It should not affect the user experience. 

Any contribution here is welcome! Actually, K8S is a new area for me. We can make this plugin better together! 😄

**Comment by gavinfish** [comment]
@runzexia any updates here? I need to do a release with #68 which will force users to update their api version for some kubernetes resources.

**Comment by runzexia** [comment]
@gavinfish There is no progress yet, I am still looking for something wrong with the classloader. If you need release, there is no problem. But I think we should mark this inconsistency in a relatively eye-catching place.

**Comment by gavinfish** [comment]
Great @runzexia! Indeed if you can fix the classloader issue and switch to kubernetes-client library, there may not be any inconsistency for the next release. The library seems to be compatible with different api versions.

**Comment by gavinfish** [comment]
Some details about the classloader issue in my opinion, the `Yaml` class will use these [codes](https://github.com/kubernetes-client/java/blob/0cc86a439c97807dbd8974ef46ebd46049e41248/util/src/main/java/io/kubernetes/client/util/Yaml.java#L118-L119) to load support models of kubernetes. In Jenkins, `Yaml.class.getClassLoader()` represents Jenkins plugins related classloader which is not compatible with the `ClassPath`. We can extend the classloader to make them compatible. But I think it may be easier here to find a place to invoke [addModelMap](https://github.com/kubernetes-client/java/blob/0cc86a439c97807dbd8974ef46ebd46049e41248/util/src/main/java/io/kubernetes/client/util/Yaml.java#L148) and manually load the initial models.

**Comment by runzexia** [comment]
@gavinfish 
The PR I opened is blocked from the core using the hpi plugin, and the method can now be called.
https://github.com/jenkinsci/kubernetes-cd-plugin/pull/81
