### ISSUE TITLE
miss 'build step' on jenkins version:2.89.2

### ISSUE THREAD

**Issue by zhangxichun** [jenkinsci/kubernetes-cd-plugin#9]
In my version:2.89.2 of jenkins 
I installed this plugin
but, I can't see 'Deploy to Kubernetes' in list of 'Add build step'
P.S. my jenkins is running as a container

**Comment by ArieShout** [comment]
I checked the behavior on Jenkins 2.89.2 but could not reproduce the issue.

Could you please paste the list of the plugins installed on your Jenkins instance? By visiting the following URL:

```
http://<jenkins>/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins
```

**Comment by zhangxichun** [comment]
yep, thx for replay

==================
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<plugins>
<shortName>blueocean-config</shortName>
<version>1.0.0-b14</version>
<shortName>subversion</shortName>
<version>2.10.2</version>
<shortName>job-dsl</shortName>
<version>1.54</version>
<shortName>momentjs</shortName>
<version>1.1.1</version>
<shortName>performance</shortName>
<version>2.0</version>
<shortName>pipeline-stage-step</shortName>
<version>2.2</version>
<shortName>branch-api</shortName>
<version>2.0.16</version>
<shortName>node-iterator-api</shortName>
<version>1.5.0</version>
<shortName>pam-auth</shortName>
<version>1.3</version>
<shortName>mapdb-api</shortName>
<version>1.0.9.0</version>
<shortName>jenkins-flowdock-plugin</shortName>
<version>1.1.8</version>
<shortName>naginator</shortName>
<version>1.17.2</version>
<shortName>azure-commons</shortName>
<version>0.2.0</version>
<shortName>matrix-project</shortName>
<version>1.7.1</version>
<shortName>blueocean-personalization</shortName>
<version>1.0.0-b14</version>
<shortName>antisamy-markup-formatter</shortName>
<version>1.5</version>
<shortName>token-macro</shortName>
<version>2.0</version>
<shortName>sse-gateway</shortName>
<version>1.10</version>
<shortName>blueocean-display-url</shortName>
<version>1.3</version>
<shortName>plain-credentials</shortName>
<version>1.3</version>
<shortName>blueocean-events</shortName>
<version>1.0.0-b14</version>
<shortName>bitbucket</shortName>
<version>1.1.5</version>
<shortName>blueocean-dashboard</shortName>
<version>1.0.0-b14</version>
<shortName>display-url-api</shortName>
<version>2.2.0</version>
<shortName>radargun</shortName>
<version>1.2</version>
<shortName>blueocean-rest</shortName>
<version>1.0.0-b14</version>
<shortName>docker-build-step</shortName>
<version>1.35</version>
<shortName>ace-editor</shortName>
<version>1.1</version>
<shortName>github-organization-folder</shortName>
<version>1.6</version>
<shortName>jquery-detached</shortName>
<version>1.2.1</version>
<shortName>pipeline-input-step</shortName>
<version>2.5</version>
<shortName>disable-failed-job</shortName>
<version>1.15</version>
<shortName>pipeline-stage-tags-metadata</shortName>
<version>1.2.5</version>
<shortName>tasks</shortName>
<version>4.50</version>
<shortName>mailer</shortName>
<version>1.20</version>
<shortName>jsch</shortName>
<version>0.1.54.1</version>
<shortName>maven-plugin</shortName>
<version>2.14</version>
<shortName>analysis-collector</shortName>
<version>1.49</version>
<shortName>cloudbees-folder</shortName>
<version>6.1.2</version>
<shortName>conditional-buildstep</shortName>
<version>1.3.5</version>
<shortName>timestamper</shortName>
<version>1.8.9</version>
<shortName>kubernetes-cd</shortName>
<version>0.1.4</version>
<shortName>blueocean</shortName>
<version>1.0.0-b14</version>
<shortName>build-with-parameters</shortName>
<version>1.3</version>
<shortName>ant</shortName>
<version>1.7</version>
<shortName>git</shortName>
<version>3.6.4</version>
<shortName>icon-shim</shortName>
<version>2.0.3</version>
<shortName>mercurial</shortName>
<version>1.57</version>
<shortName>docker-plugin</shortName>
<version>0.16.2</version>
<shortName>managed-scripts</shortName>
<version>1.2.4</version>
<shortName>docker-workflow</shortName>
<version>1.9.1</version>
<shortName>blueocean-web</shortName>
<version>1.0.0-b14</version>
<shortName>apache-httpcomponents-client-4-api</shortName>
<version>4.5.3-2.0</version>
<shortName>pipeline-model-declarative-agent</shortName>
<version>1.1.1</version>
<shortName>ssh-slaves</shortName>
<version>1.24</version>
<shortName>gradle</shortName>
<version>1.28</version>
<shortName>git-client</shortName>
<version>2.7.0</version>
<shortName>pipeline-build-step</shortName>
<version>2.4</version>
<shortName>build-name-setter</shortName>
<version>1.6.5</version>
<shortName>pipeline-milestone-step</shortName>
<version>1.3.1</version>
<shortName>workflow-scm-step</shortName>
<version>2.5</version>
<shortName>ws-cleanup</shortName>
<version>0.34</version>
<shortName>blueocean-pipeline-api-impl</shortName>
<version>1.0.0-b14</version>
<shortName>authentication-tokens</shortName>
<version>1.3</version>
<shortName>workflow-step-api</shortName>
<version>2.14</version>
<shortName>vsphere-cloud</shortName>
<version>2.14</version>
<shortName>email-ext</shortName>
<version>2.61</version>
<shortName>structs</shortName>
<version>1.10</version>
<shortName>pipeline-rest-api</shortName>
<version>2.9</version>
<shortName>ldap</shortName>
<version>1.18</version>
<shortName>workflow-api</shortName>
<version>2.24</version>
<shortName>resource-disposer</shortName>
<version>0.3</version>
<shortName>favorite</shortName>
<version>2.0.4</version>
<shortName>git-server</shortName>
<version>1.7</version>
<shortName>bouncycastle-api</shortName>
<version>2.16.0</version>
<shortName>groovy</shortName>
<version>1.30</version>
<shortName>windows-slaves</shortName>
<version>1.2</version>
<shortName>workflow-durable-task-step</shortName>
<version>2.16</version>
<shortName>workflow-cps-global-lib</shortName>
<version>2.9</version>
<shortName>ssh-credentials</shortName>
<version>1.13</version>
<shortName>build-timeout</shortName>
<version>1.19</version>
<shortName>description-setter</shortName>
<version>1.10</version>
<shortName>pipeline-stage-view</shortName>
<version>2.9</version>
<shortName>pipeline-model-definition</shortName>
<version>1.2.5</version>
<shortName>ansicolor</shortName>
<version>0.4.3</version>
<shortName>external-monitor-job</shortName>
<version>1.6</version>
<shortName>variant</shortName>
<version>1.1</version>
<shortName>javadoc</shortName>
<version>1.0</version>
<shortName>analysis-core</shortName>
<version>1.81</version>
<shortName>warnings</shortName>
<version>4.58</version>
<shortName>workflow-cps</shortName>
<version>2.41</version>
<shortName>checkstyle</shortName>
<version>3.47</version>
<shortName>blueocean-rest-impl</shortName>
<version>1.0.0-b14</version>
<shortName>pipeline-model-extensions</shortName>
<version>1.2.5</version>
<shortName>workflow-basic-steps</shortName>
<version>2.3</version>
<shortName>github</shortName>
<version>1.28.1</version>
<shortName>project-inheritance</shortName>
<version>1.5.3</version>
<shortName>matrix-auth</shortName>
<version>1.7</version>
<shortName>pipeline-model-api</shortName>
<version>1.2.5</version>
<shortName>pmd</shortName>
<version>3.46</version>
<shortName>metrics</shortName>
<version>3.1.2.9</version>
<shortName>workflow-job</shortName>
<version>2.11.2</version>
<shortName>run-condition</shortName>
<version>1.0</version>
<shortName>workflow-multibranch</shortName>
<version>2.16</version>
<shortName>scm-api</shortName>
<version>2.2.6</version>
<shortName>script-security</shortName>
<version>1.39</version>
<shortName>durable-task</shortName>
<version>1.17</version>
<shortName>pipeline-graph-analysis</shortName>
<version>1.3</version>
<shortName>config-file-provider</shortName>
<version>2.16.4</version>
<shortName>github-branch-source</shortName>
<version>2.3.2</version>
<shortName>blueocean-i18n</shortName>
<version>1.0.0-b14</version>
<shortName>blueocean-autofavorite</shortName>
<version>0.5</version>
<shortName>rebuild</shortName>
<version>1.25</version>
<shortName>github-api</shortName>
<version>1.90</version>
<shortName>pipeline-github-lib</shortName>
<version>1.0</version>
<shortName>docker-commons</shortName>
<version>1.5</version>
<shortName>workflow-aggregator</shortName>
<version>2.5</version>
<shortName>blueocean-commons</shortName>
<version>1.0.0-b14</version>
<shortName>credentials</shortName>
<version>2.1.16</version>
<shortName>workflow-support</shortName>
<version>2.14</version>
<shortName>junit</shortName>
<version>1.6</version>
<shortName>handlebars</shortName>
<version>1.1.1</version>
<shortName>promoted-builds</shortName>
<version>2.28</version>
<shortName>credentials-binding</shortName>
<version>1.13</version>
<shortName>parameterized-trigger</shortName>
<version>2.35.2</version>
<shortName>jackson2-api</shortName>
<version>2.7.3</version>
<shortName>view-job-filters</shortName>
<version>1.27</version>
<shortName>blueocean-jwt</shortName>
<version>1.0.0-b14</version>
<shortName>support-core</shortName>
<version>2.38</version>
</plugins>

**Comment by ArieShout** [comment]
This should be related to https://github.com/jenkinsci/azure-commons-plugin/issues/18

Please upgrade `azure-commons` to the latest version. Version `0.2.0` had some compatibility issue which breaks the `kubernetes-cd`.

**Comment by ArieShout** [comment]
Close as no further response from the user.
