### ISSUE TITLE
Support for PersistentVolumeClaim

### ISSUE THREAD

**Issue by tkuther** [jenkinsci/kubernetes-cd-plugin#90]
It would be great if PersistentVolumeClaim was a supported resource.

**Comment by runzexia** [comment]
You can try the RC version. In the RC version, we switched the sdk used, and we can't release a full version yet.
Https://github.com/jenkinsci/kubernetes-cd-plugin/pull/94
Any feedback on the RC version will be very useful

**Comment by tkuther** [comment]
Tested. Works!

Thanks a lot!

**Comment by ijazm123** [comment]
rc version?
